/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HistoryEntry { 'songId' : SongId, 'timestamp' : Time }
export type PlaylistId = bigint;
export interface PlaylistView {
  'id' : PlaylistId,
  'name' : string,
  'songs' : Array<SongId>,
}
export interface Song {
  'title' : string,
  'duration' : string,
  'thumbnail' : string,
  'lyrics' : [] | [string],
  'channel' : string,
  'videoId' : SongId,
}
export type SongId = string;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSongToPlaylist' : ActorMethod<[PlaylistId, SongId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cacheLyrics' : ActorMethod<[SongId, string], undefined>,
  'cacheSong' : ActorMethod<[Song], undefined>,
  'createPlaylist' : ActorMethod<[string], PlaylistId>,
  'deletePlaylist' : ActorMethod<[PlaylistId], undefined>,
  'fetchLyrics' : ActorMethod<[string, string], string>,
  'getAllPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLikedSongs' : ActorMethod<[], Array<Song>>,
  'getListeningHistory' : ActorMethod<[], Array<HistoryEntry>>,
  'getPlaylist' : ActorMethod<[PlaylistId], [] | [PlaylistView]>,
  'getSong' : ActorMethod<[SongId], [] | [Song]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeSong' : ActorMethod<[SongId], undefined>,
  'recordListening' : ActorMethod<[SongId], undefined>,
  'removeSongFromPlaylist' : ActorMethod<[PlaylistId, SongId], undefined>,
  'renamePlaylist' : ActorMethod<[PlaylistId, string], undefined>,
  'reorderPlaylist' : ActorMethod<[PlaylistId, Array<SongId>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlikeSong' : ActorMethod<[SongId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];