/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlaylistId = IDL.Nat;
export const SongId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Song = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnail' : IDL.Text,
  'lyrics' : IDL.Opt(IDL.Text),
  'channel' : IDL.Text,
  'videoId' : SongId,
});
export const PlaylistView = IDL.Record({
  'id' : PlaylistId,
  'name' : IDL.Text,
  'songs' : IDL.Vec(SongId),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const HistoryEntry = IDL.Record({
  'songId' : SongId,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSongToPlaylist' : IDL.Func([PlaylistId, SongId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cacheLyrics' : IDL.Func([SongId, IDL.Text], [], []),
  'cacheSong' : IDL.Func([Song], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [PlaylistId], []),
  'deletePlaylist' : IDL.Func([PlaylistId], [], []),
  'fetchLyrics' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getListeningHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(PlaylistView)], ['query']),
  'getSong' : IDL.Func([SongId], [IDL.Opt(Song)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeSong' : IDL.Func([SongId], [], []),
  'recordListening' : IDL.Func([SongId], [], []),
  'removeSongFromPlaylist' : IDL.Func([PlaylistId, SongId], [], []),
  'renamePlaylist' : IDL.Func([PlaylistId, IDL.Text], [], []),
  'reorderPlaylist' : IDL.Func([PlaylistId, IDL.Vec(SongId)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeSong' : IDL.Func([SongId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlaylistId = IDL.Nat;
  const SongId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Song = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnail' : IDL.Text,
    'lyrics' : IDL.Opt(IDL.Text),
    'channel' : IDL.Text,
    'videoId' : SongId,
  });
  const PlaylistView = IDL.Record({
    'id' : PlaylistId,
    'name' : IDL.Text,
    'songs' : IDL.Vec(SongId),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const HistoryEntry = IDL.Record({ 'songId' : SongId, 'timestamp' : Time });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSongToPlaylist' : IDL.Func([PlaylistId, SongId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cacheLyrics' : IDL.Func([SongId, IDL.Text], [], []),
    'cacheSong' : IDL.Func([Song], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [PlaylistId], []),
    'deletePlaylist' : IDL.Func([PlaylistId], [], []),
    'fetchLyrics' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getListeningHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
    'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(PlaylistView)], ['query']),
    'getSong' : IDL.Func([SongId], [IDL.Opt(Song)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeSong' : IDL.Func([SongId], [], []),
    'recordListening' : IDL.Func([SongId], [], []),
    'removeSongFromPlaylist' : IDL.Func([PlaylistId, SongId], [], []),
    'renamePlaylist' : IDL.Func([PlaylistId, IDL.Text], [], []),
    'reorderPlaylist' : IDL.Func([PlaylistId, IDL.Vec(SongId)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeSong' : IDL.Func([SongId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };